server:
  port: 9123
  servlet:
    context-path: /demo_es #配置项目名称


spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.8.3.166:9300
      repositories:
        enabled: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/** #
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.9.2.88:3306/eichong_stat?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    openMulti: true
    type: com.zaxxer.hikari.HikariDataSource
#  spring.datasource.hikari.minimum-idle=5
#  spring.datasource.hikari.maximum-pool-size=15
#  spring.datasource.hikari.auto-commit=true
#  spring.datasource.hikari.idle-timeout=30000
#  spring.datasource.hikari.pool-name=DatebookHikariCP
#  spring.datasource.hikari.max-lifetime=1800000
#  spring.datasource.hikari.connection-timeout=30000
#  spring.datasource.hikari.connection-test-query=SELECT 1

    idle-timeout: 30000
    multi:
    - key: slaveDB
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.9.2.58:3306/eichong?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      idle-timeout: 20000
#      type: com.alibaba.druid.pool.DruidDataSource
    - key: masterDB
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.9.2.88:3306/eichong?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      idle-timeout: 20000
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1




  # Redis数据库索引（默认为0）
  redis:
    # Redis服务器地址
    host: 10.9.2.88
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 0987654321rfvujmtgbyhn
    database: 4
    timeout: 100
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 0
        # 连接池中的最小空闲连接
        min-idle: 0



  #logback
  profiles:
    #指定读取配置文件:dev(开发环境),prod(生产环境),qa(测试环境)
    active: dev

#配置sql-log输出
logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    com.wanma.demoes.mapper: debug
  #开发环境
  #java -jar app.jar --spring.profiles.active=dev--server.port=8060
  #测试环境
  #java -jar app.jar --spring.profiles.active=qa --server.port=8060
  #生产环境
  #java -jar app.jar --spring.profiles.active=prod --server.port=8060

  #nohup java -jar data_center.jar --spring.profiles.active=dev > data_center.log 2>&1 &
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappings/*Mapper.xml
  type-aliases-package: com.wanma.demoes.entity
